import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';
import 'package:google_fonts/google_fonts.dart';
List<Map<String,dynamic>>rechrplan=[
  {
    'number':"49",
    'name':"Validity",
    'validity':"1 day",
    'data':"Data",
    'pack':"6GB/pack",
  },
  {
    'number':"148",
    'name':"Data",
    'validity':"15GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"118",
    'name':"Data",
    'validity':"12GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"301",
    'name':"Data",
    'validity':"50GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"65",
    'name':"Data",
    'validity':"4GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"19",
    'name':"Data",
    'validity':"3GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"58",
    'name':"Data",
    'validity':"3GB/pack",
    'data':"",
    'pack':"",
  },
  {
    'number':"90",
    'name':"Data",
    'validity':"15GB/pack",
    'data':"",
    'pack':"",
  },
];